version: '3'
services:
  citus:
    image: citusdata/citus
    container_name: materialized-poc-postgres
    restart: always
    #ports:
    #  - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - postgres_net
    logging:
      driver: none
  pgadmin:
    image: dpage/pgadmin4
    container_name: materialized-poc-pgadmin
    restart: always
    ports:
      - "5000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=joffin@tunerlabs.com
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - postgres_net
    logging:
      driver: none
  materialized-poc:
    build: './'
    container_name: materialized-poc
    image: elevate/materialized-poc:1.0
    volumes:
      - ./src/:/var/src
    ports:
      - '3045:3045'
    command: ['nodemon', 'app.js']
    depends_on:
      - citus
    networks:
      - postgres_net
networks:
  postgres_net:
    external: false
volumes:
  postgres-data:
